config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # This defines a `route` rule that says when we receive a GET
  # request with the URL `/`, handle it with the `WelcomeController`
  # with the `index` action inside that controller.
  # get('/', { to: 'welcome#index', as: 'root'})
  root 'welcome#index'
  # Question Routes
  # get('/questions/new', to: 'questions#new', as: :new_question)
  # post('/questions', to:'questions#create', as: :questions)

  # get('/questions', to: 'questions#index')
  #   #new_question_path or new_question_url
  # get('/questions/:id', to: 'questions#show', as: :question)
  # #question_path(id) or question_url(id)
  # delete('/questions/:id', to: 'questions#destroy')
  # get('/questions/:id/edit', to: 'questions#edit', as: :edit_question)
  # patch('/questions/:id', to: 'questions#update')


  # resources method will gneerate all CRUD routes following
  # RESTful conventions for a resource. It will assume there 
  # is a controller named after the first argument pluralized
  # and PascalCased (i.e. QuestionsController)  
  resources :questions do 
    # Routes written inside of a block passed to a 
    # `resources` method will be pre-fixed by a path 
    # correpsonding to the passed in symbol (:questions)
    # In this case, all nested routes will be prfxied
    # with `/questions/:question_id`

    resources :answers, only: [:create, :destroy]
    # resources :answers, except: [:new, :edit, :update, :index, :show]
    # the shallow: true named argument will seperate 
    # routes that require the parent from those that don't 
    # Routes that require the parent (e.g. index, new, create) won't change (They will still be prefixed 
    # with /questions/:question_id )
    # Routes that don't require the parent (e.g. show, edit,
    # update, destroy) will have the parent prefix removed. 
    # Example: 
    # /questions/10/likes/9/edit becomes /likes/9/edit
    resources :likes, shallow: true, only: [ :create, :destroy]
    # resources :answers, except: [:new, :edit, :update, :index, :show]
    # Use the `on:` named argument to specify how a nested 
    # route will behave relative to its parent. 

    # `on: :collection` means that it acts on the entire 
    # resource. All questions in this case. 
    # new and create act on collection 
    
    # `on: :member` means that it acts on single resource. 
    # A single question in this case. edit, update, destroy
    # show are member routes  
    get :liked, on: :collection
  end

  get '/contacts/new', to: 'contacts#new'
  post '/contacts', to: 'contacts#create'

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  get "/auth/github", as: :sign_in_with_github
  get "/auth/:provider/callback", to: "callbacks#index"


  resources :job_posts

  # The namespace method in Rails routes makes it so 
  # it will automatically look in a directory api, then 
  # in a directory v1 for QuestionsController.

  # The option `defaults: { format: :json }` will
  namespace :api, defaults: { format: :json } do 
    # /api...
    namespace :v1 do 
      # /api/v1...
      resources :questions
      #/api/v1/questions
      resource :session, only: [:create, :destroy]
      #/api/v1/session 
      resources :users, only: [:create, :update] do
        #api/v1/users/current
        get :current, on: :collection 
        #default
        #api/v1/users/:id/current
      end
    end
  end

  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post]
  )
 
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user
  # Adding `dependent: :destroy` tells Rails to delete
  # associated records before deleting the record itself.
  # In this case, when a question is deleted, its answers are 
  # deleted first to satisfy the foreign_key constraint 
  
  # You can also use `dependent: :nullify` which will casuse 
  # all associated answers to have their question_id column 
  # set to NULL before the question is destroyed. 
  
  # If you don't set either `dependent` option, you can end up
  # with answers in your db referencing question_ids hat 
  # no longer exist, likely leading to errors.
  # ALWAYS SET A DEPENDENT OPTION TO HELP MAINTAIN REFERENTIAL 
  # INTEGRITY 
  has_many(:answers, dependent: :destroy)
  has_many :likes, dependent: :destroy
  # The `has_many` below is dependent on the existence of 
  # `has_many :likes` above. If the above doesn't exist then you 
  # will get an error (if the one above comes after you will 
  # also get an error) 
  has_many :likers, through: :likes, source: :user 

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings#, source: :tag
  # If the name of the association is the same as the 
  # as the source singularized (i.e. tag), the :source 
  # named argument can be omitted. 

  # has_many :answers adds the following instance methods
  # to the question model:
  # answers
  # answers<<(object, ...)
  # answers.delete(object, ...)
  # answers.destroy(object, ...)
  # answers=(objects)
  # answers_singular_ids
  # answers_singular_ids=(ids)
  # answers.clear
  # answers.empty?
  # answers.size
  # answers.find(...)
  # answers.where(...)
  # answers.exists?(...)
  # answers.build(attributes = {}, ...)
  # answers.create(attributes = {})
  # answers.create!(attributes = {})
  # answers.reload


  #  Create validations by using the 'validates'
  # method. The arguments are (in order):
  # - A column names a symbol,
  # - Named arguments corresponding to validation rules

  # To read more on validations https://guides.rubyonrails.org/active_record_validations.html
  
  # Validations
  # rails has built in methods which allow us to create validations really easily
  validates :title, presence: true # will make sure a question has a title before saving it

  # validate uniquess of title
  validates :title, uniqueness: true
  
  # validating length of the body
  validates :body, length: {minimum: 5, maximum: 500}

  #
  validates :view_count, numericality: {greater_than_or_equal_to: 0}

  validates :title, uniqueness: {scope: :body}

  # custom validation
  validate(:no_monkey)


  # scope(:recent, lambda { order(created_at: :desc).limit(10) })
  scope(:recent, -> { order(created_at: :desc).limit(10) })
  # Question Model
  # This got generated with the rails g model question title:string body:text
  # Question class inherits everything from ApplicationRecord

  # Rails will add attr_accessors for all columns of the table (i.e. id, title, body, created_at, updated_at)

  # Rails HOOK

  # before_validation is lifecycle callback method
  # that allows us to respond to events in an objects
  # lifecycle. (i.e. being validated, saved, updated etc.). These methods take a symbol named after a method and calls that method at the appropriate time
  before_validation :capitalize_title #before saving a record, execute the capitalize_title method
  before_validation :set_default_view_count

  # Getter
  def tag_names 
    self.tags.map{ |t| t.name }.join(", ")
  end

  # Appending `=` at the end of a method name, allows us to imolement 
  # a setter. 
  # Example: q.tag_names = "fiction,horror"
  
  def tag_names=(rhs) 
    self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
      # Finds the first record with the given attributes, OR 
      # initializes a record (Tag.new) with the given attributes 
      # if one is not found. 
      Tag.find_or_initialize_by(name: tag_name)
    end
  end

  
  private

  def capitalize_title
    self.title.capitalize!
  end

  # def self.recent
  #   order(created_at: :desc).limit(10)
  # end
  # ^ scopes like the above are such a commonly used
  # feature in Rails, there's a way to create them
  # quicker. It takes a name, and a lambda as a callback


  def no_monkey
    # &. is the safe navigator operator. It is used like the . operator to call methods on an object only if they exist
    if body&.downcase&.include?("monkey")
      # if a body of a question has the word "monkey" in it give us an error.

      # errors.add is used to add an error to the instance. It accepts 2 arguments
      # 1) the column/property you want the error to be on
      # 2) the error message
      self.errors.add(:body, "must not have monkeys")
    end
  end

  def set_default_view_count
    # If you are writing to an attribute accessor,
    # you must prefix with self, which you don't have
    # to do if you are just reading it.
    self.view_count ||= 0
    # self.view_count || self.view_count = 0
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_question, only: [:show, :edit, :update, :destroy]

    def create
        question = Question.new question_params
        question.user = current_user
        if question.save
            render json: { id: question.id }
        else 
            render(
            json: {  errors: question.errors },
            status: 422 # Unprocessable Entity
            )
        end
    end

    def index
        questions = Question.order(created_at: :desc)
        # This allows us to use the 
        # QuestionCollectionSerlializer to render json of 
        # questions in this list in order to keep the data 
        # limited to the minimum we need.
        render json: questions, each_serializer: QuestionCollectionSerializer    
    end

    def show        
        render json: @question, include: [:author, {answers: [:author]}]
    end

    def edit
    end

    def update
        if @question.update question_params
            render json: {id: @question.id}
        else
            render(
                json: { errors: @question.errors },
                status: 422 # Unprocessable Entity
            )
        end
    end

    def destroy
        @question.destroy
        render(json: {status: 200}, status: 200)
    end

    private

    def find_question
        @question = Question.find params[:id]
    end

    def question_params
        params.require(:question).permit(:title, :body)
    end



end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_question, only: [:edit,:update,:show, :destroy]
    before_action :authorize!, only: [:edit,:update,:destroy]


    def new
        @question=Question.new
    end

    def create
        @question = Question.new question_params
        @question.user = current_user

        if @question.save # perform validation and if succesful it will save indb
            flash[:notice] = 'Question Created Successfully'
            redirect_to question_path(@question.id)
        else
            render :new
        end
    end

    def edit
        
    end

    def update
        if @question.update question_params
            flash[:notice] = 'Question updated Successfully'
            redirect_to question_path(@question.id)
        else
            render :edit
        end
    end

   
    def index 
        if params[:tag]
            @tag = Tag.find_or_initialize_by(name: params[:tag])
            @questions = @tag.questions.order(created_at: :desc)
        else
            @questions = Question.order(created_at: :desc)
        end
        respond_to do |format|
            format.html { render :index }
            format.json { render json: @questions }
            # format.csv { render plain: 'blah, blah, blah'}
        end
    end


    def show
        @new_answer = Answer.new
        @answers = @question.answers.order(created_at: :desc)
        # @answer = @question.answers.all
        # @question.view_count += 1
        # @question.save

        # The method `update_columns` works just like `update`. However,
        # it will skip validations, skip callbacks and not update `updated_at`.
        # Unless, you have a very good reason to use this DO NOT USE IT.
        @question.update_columns(view_count: @question.view_count+1) 
        @like = @question.likes.find_by(user: current_user)
        # respond_to do |format|
            # format.json { render json: @question }
            # format.csv { render plain: 'blah, blah, blah'}
        # end
    end

    def destroy
        @question.destroy
        redirect_to questions_path
    end

    def liked
        @questions = current_user.liked_questions.order('likes.created_at DESC')
    end


    private
    
    def find_question
        @question=Question.find params[:id]
    end

    def question_params
        params.require(:question).permit(:title, :body, :tag_names)
    end

    def authorize! 
        unless can?(:crud, @question)
            redirect_to root_path, alert: 'Not Authorized' 
        end
    end

end

app/views/questions/_form.html.erb
<%#
In Rails, a template whose name begins with
an "_" is considered a partial.
To create a form for a resource (i.e. a model), use the `form_with`
helper instead of the `form_tag`. It's usual arguments are:
- A named arg. `model` which is assigned an instance of a model
  (e.g. a new question)
- A named arg. `local` which will prevent the form from submitting
  its data using AJAX.
- A block that is passed the `form` object wherein we build
  the HTML inside the form (e.g. labels, inputs, submission buttons, etc)
All data from the input fields a form built with this will have its
name-value nested in a hash named after the class of the passed in model.
(e.g. <input name="question[title]"> => { "question": { "title": "What?" } })
%>

<%= form_with(model: @question, local: true) do |form|%>
<div>
    <% if @question.errors.present?%>
    <%= @question.errors.full_messages.join(', ')%>
    <% end %>
</div>
<div>
    <%= form.label :title%><br>
    <%= form.text_field :title %>
</div>
<div>
    <%= form.label :body %><br>
    <%= form.text_area :body, cols: 50, rows:5%>  
</div>
<div>
    <%#= form.label :tag_ids, "Tags" %>
    <%#= form.collection_check_boxes :tag_ids, Tag.all, :id, :name do |b| %>
            <%#= b.check_box %>
            <%#= b.text.humanize %>
    <%# end %>
    <%= form.label :tag_names %>
    <%= form.text_field :tag_names %>

</div>
<br>
    <%= form.submit %>
<% end %>

<script>
    // Documentation for selectize.js:
    // https://selectize.github.io/selectize.js/
    // For description of options that are usable go to:
    // https://github.com/selectize/selectize.js/blob/master/docs/usage.md
    $('#question_tag_names').selectize({
        delimiter: ',',
        persist: false,
        labelField: "name",
        valueField: "name",
        searchField: "name",
        options: <%= Tag.select(:name).to_json(except: [:id]).html_safe %>,
        create: function(input) {
            return {
                name: input
            }
        }
    });
</script>

app/views/questions/_list.html.erb
<%@questions.each do |question|%>
<div>
    <h2><%= link_to(question.title,question_path(question.id)) %></h2>
    <p><%= question.body %></p>
    <p>Posted <%=time_ago_in_words(question.created_at)%> ago</p>
</div>
<%end%>

app/views/questions/edit.html.erb
<h1>Edit Form</h1>
<%= render 'form' %>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<% if @tag.present? %>
    <h6>
        Showing questions tagged by 
        <span class="badge badge-pill badge-primary">
            <%= @tag.name %>
        </span>
    </h6>
<% end %>
<%= render 'list'%>

app/views/questions/liked.html.erb
<h1>Your Liked Questions</h1>
<%= render 'list' %>

app/views/questions/new.html.erb
<h1>New Form </h1>
<%= render 'form' %>

app/views/questions/show.html.erb
<h1>Question</h1>
<h1><%= @question.title %></h1>
<p><%= @question.body %></p>
<% unless @question.tags.empty?  %>
    <p>
    Tags: 
    <% @question.tags.each do |tag| %>
        <%= link_to(
            tag.name, questions_path(tag: tag.name),
            class: 'badge badge-pill badge-primary'
        ) %>
    <% end %>
    </p>
<% end %>
<%#= @question.tags.map{ |t| t.name }.join(", ") %>
<%#= @question.tags.map(&:name).join(", ") %>
<p>Asked <%= time_ago_in_words(@question.created_at) %> ago</p>
<p>Last edited <%= time_ago_in_words(@question.updated_at) %></p>
<small> <%= pluralize(@question.view_count,"time") %></small><br/>
    <% if can? :destroy, @question %>
        <%= link_to("Delete", question_path(@question), method: :delete, data:{confirm:'Are you sure?' }) %>
        <br />
    <% end %>
<% if can? :update, @question %>
    <%= link_to 'Edit', edit_question_path(@question.id)%>
<% end %>
<br>
<% if @like.present? && can?(:destroy, @like) %>
    <%=link_to(
        "Unlike",
        like_path(@like),
        method: :delete
    )%> |
<% elsif can?(:like, @question) %>
    <%=link_to(
        "Like",
        question_likes_path(@question),
        method: :post
    )%> |
<% end %>
<small><%= pluralize(@question.likes.count, "like") %></small>
<section>
<h1>Answers</h1>

<%= form_with(model: [@question, @new_answer], local: true) do |f| %>
    <% if @new_answer.errors.present? %>
        <p class="form-errors">
            <%= @new_answer.errors.full_messages.join(", ") %>
        </p>
    <% end %>
    <div class="form-group">
        <%= f.text_area(
            :body,
            cols: 50,
            rows: 3,
            placeholder:"What are your thoughts?",
            class: "form-control"
        ) %>
    </div>

    <%= f.submit 'Answer' %>
<% end %>

<hr>
<ul class="answer-list">
    <% @answers.each do |answer| %>
        <li>
            <%= answer.body %> <br>
            <% if can? :crud, answer %>
                <small>
                    <%= link_to(
                        "Delete",
                        question_answer_path(@question,answer),
                        method: :delete,
                        data:{
                            confirm: "Are you sure?"
                        }
                    ) %>
                </small>
            <% end %>
            <small>
                Answered <%= time_ago_in_words(answer.created_at) %> ago 
            </small>
        </li>
    <% end %>
</ul>
</section>