config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # This defines a `route` rule that says when we receive a GET
  # request with the URL `/`, handle it with the `WelcomeController`
  # with the `index` action inside that controller.
  # get('/', { to: 'welcome#index', as: 'root'})
  root 'welcome#index'
  # Question Routes
  # get('/questions/new', to: 'questions#new', as: :new_question)
  # post('/questions', to:'questions#create', as: :questions)

  # get('/questions', to: 'questions#index')
  #   #new_question_path or new_question_url
  # get('/questions/:id', to: 'questions#show', as: :question)
  # #question_path(id) or question_url(id)
  # delete('/questions/:id', to: 'questions#destroy')
  # get('/questions/:id/edit', to: 'questions#edit', as: :edit_question)
  # patch('/questions/:id', to: 'questions#update')


  # resources method will gneerate all CRUD routes following
  # RESTful conventions for a resource. It will assume there 
  # is a controller named after the first argument pluralized
  # and PascalCased (i.e. QuestionsController)  
  resources :questions do 
    # Routes written inside of a block passed to a 
    # `resources` method will be pre-fixed by a path 
    # correpsonding to the passed in symbol (:questions)
    # In this case, all nested routes will be prfxied
    # with `/questions/:question_id`

    resources :answers, only: [:create, :destroy]
    # resources :answers, except: [:new, :edit, :update, :index, :show]
    # the shallow: true named argument will seperate 
    # routes that require the parent from those that don't 
    # Routes that require the parent (e.g. index, new, create) won't change (They will still be prefixed 
    # with /questions/:question_id )
    # Routes that don't require the parent (e.g. show, edit,
    # update, destroy) will have the parent prefix removed. 
    # Example: 
    # /questions/10/likes/9/edit becomes /likes/9/edit
    resources :likes, shallow: true, only: [ :create, :destroy]
    # resources :answers, except: [:new, :edit, :update, :index, :show]
    # Use the `on:` named argument to specify how a nested 
    # route will behave relative to its parent. 

    # `on: :collection` means that it acts on the entire 
    # resource. All questions in this case. 
    # new and create act on collection 
    
    # `on: :member` means that it acts on single resource. 
    # A single question in this case. edit, update, destroy
    # show are member routes  
    get :liked, on: :collection
  end

  get '/contacts/new', to: 'contacts#new'
  post '/contacts', to: 'contacts#create'

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  get "/auth/github", as: :sign_in_with_github
  get "/auth/:provider/callback", to: "callbacks#index"


  resources :job_posts

  # The namespace method in Rails routes makes it so 
  # it will automatically look in a directory api, then 
  # in a directory v1 for QuestionsController.

  # The option `defaults: { format: :json }` will
  namespace :api, defaults: { format: :json } do 
    # /api...
    namespace :v1 do 
      # /api/v1...
      resources :questions
      #/api/v1/questions
      resource :session, only: [:create, :destroy]
      #/api/v1/session 
      resources :users, only: [:create, :update] do
        #api/v1/users/current
        get :current, on: :collection 
        #default
        #api/v1/users/:id/current
      end
    end
  end

  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post]
  )
 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAnswers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Bangers&display=swap" rel="stylesheet">
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAbPzDWGwq7BA7yeMFFVl66aX0Tq692HFs"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/markerclustererplus/2.1.4/markerclusterer.min.js"></script>

  </head>

  <body>
    <nav class = "navbar">
    <div>
      <% if user_signed_in? %>
        Hello <strong><%= link_to current_user.full_name, user_path(current_user.id) %></strong>,
        <%= link_to "Logout", session_path, method: :delete,
          data: {confirm: "Are you sure you want to log out?"} %>
          |
        <%= link_to "Liked Questions", liked_questions_path %>
      <% else %>
        <%= link_to "Login", new_session_path %> |
        <%= link_to "Sign Up", new_user_path %> |
        <%= link_to "Sign in with Github", sign_in_with_github_path %>
      <% end %>
    </div>
    <div>
      <%=link_to('Home', root_path)%>
       |
      <%=link_to('All Questions', questions_path)%>
       |
      <%=link_to('New Questions', new_question_path)%>
       |
      <%=link_to('Contact Us', contacts_new_path)%>
    </div>
    </nav>
    <p>
    <%#= flash[:notice] || flash[:alert]%>
    <% flash.each do |type, message| %>
      <div class="flash flash-<%= type %>">
        <%= message %>
      </div>
    <% end %>
    </p>
    <%= yield %>
  </body>
</html>